/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thoughtworks.capability;

import org.junit.Test;

import java.util.Arrays;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertThat(1).isEqualTo(1);
        assertThat(Arrays.asList(1, 2)).isEqualTo(Arrays.asList(1, 2));
    }
}
